name: Envoy MQTT Proxy
version: "1.0.0"
slug: envoy-mqtt
description: Envoy TCP proxy for MQTT failover
url: https://github.com/7290903/envoy/tree/main/envoy-mqtt
startup: services
boot: auto
host_network: true
privileged: true
schema: {}
arch:
  - amd64
  - aarch64
  - armv7
